### ISSUE TITLE
How to trigger a specific job ?

### ISSUE THREAD

**Issue by PaulLesur** [zivkaziv/circleci-trigger-github-action#1]
Hi ! 
I just wanted to know how you can trigger a specific job in a specific CircleCI Workflow. As I read in the Readme.md, the inputs are org, repo and branch but I don't see any option to specify the job to trigger.

**Comment by zivkaziv** [comment]
Hey Paul,
Thank you for your question...

Basically the action is sending an API request to circleCI according to their structure defined here(https://circleci.com/docs/2.0/api-job-trigger/)

So job is the combination of:
 - <org> is a placeholder variable and refers to the name of your CircleCI organization.
 - <repo> is a placeholder variable and refers to the name of your repository.
 - <branch> is a placeholder variable and refers to the name of your branch.

Let me know if it helps

**Comment by PaulLesur** [comment]
Hi, 
Thank you for your answer. I was searching for a way to approve a job on a specific workflow using a Github Action, I managed to do it using CircleCI / Github APIs and jq.

**Comment by zivkaziv** [comment]
Do you want to submit A PR to support this scenario?

**Comment by zivkaziv** [comment]
I'm closing this issue
